language: java

jdk:
  - openjdk7
  - oraclejdk7

env:
  # global env vars are injected into the environment of all build configs
  global:
    - TRAVIS_MYSQL5_DBHOST=127.0.0.1
    - TRAVIS_MYSQL5_DBPORT=3306
    - TRAVIS_MYSQL5_DBUSER=travis
    - TRAVIS_MYSQL5_DBPASS=
    - TRAVIS_MYSQL5_DBNAME_MGMT=mysql
    - TRAVIS_MYSQL5_DBUSER_MGMT=root
    - TRAVIS_MYSQL5_DBPASS_MGMT=
    - TRAVIS_PGSQL8_DBHOST=127.0.0.1
    - TRAVIS_PGSQL8_DBPORT=5432
    - TRAVIS_PGSQL8_DBUSER=deployment
    - TRAVIS_PGSQL8_DBPASS=password1
    - TRAVIS_PGSQL8_DBNAME_MGMT=postgres
    - TRAVIS_PGSQL8_DBUSER_MGMT=postgres
    - TRAVIS_PGSQL8_DBPASS_MGMT=

  # matrix env vars generate a new build config per set
  # we need to run the two test groups separately due to active_sql_format_autoloader
  matrix:
    - DBSTEWARD_SQLFORMAT=pgsql8
#    - DBSTEWARD_SQLFORMAT=mysql5

before_script:
  - if [[ "$DBSTEWARD_SQLFORMAT" == "pgsql8" ]]; then psql -U postgres -d postgres -c "CREATE USER dbsteward_ci WITH SUPERUSER CREATEDB CREATEROLE PASSWORD 'password1';"; fi
  - if [[ "$DBSTEWARD_SQLFORMAT" == "pgsql8" ]]; then PGPASSWORD=password1 psql -U dbsteward_ci -d postgres -c "CREATE DATABASE someapp;"; fi
  - if [[ "$DBSTEWARD_SQLFORMAT" == "pgsql8" ]]; then PGPASSWORD=password1 psql -U dbsteward_ci -d postgres -c "CREATE ROLE someapp;"; fi
  - if [[ "$DBSTEWARD_SQLFORMAT" == "pgsql8" ]]; then PGPASSWORD=password1 psql -U dbsteward_ci -d postgres -c "CREATE ROLE someapp_readonly;"; fi
  - if [[ "$DBSTEWARD_SQLFORMAT" == "pgsql8" ]]; then PGPASSWORD=password1 psql -U dbsteward_ci -d postgres -c "DROP DATABASE someapp;"; fi
  - mvn clean
  - mvn install

# by default, travis runs "mvn test", but we want to make sure that after installing the plugin, the examples work
script: ./script/ci/run_examples.sh
