language: java

jdk:
  - openjdk7
#  - oraclejdk7

env:
  # global env vars are injected into the environment of all build configs
  global:
    - TRAVIS_MYSQL5_DBHOST=127.0.0.1
    - TRAVIS_MYSQL5_DBPORT=3306
    - TRAVIS_MYSQL5_DBUSER=travis
    - TRAVIS_MYSQL5_DBPASS=
    - TRAVIS_MYSQL5_DBNAME_MGMT=mysql
    - TRAVIS_MYSQL5_DBUSER_MGMT=root
    - TRAVIS_MYSQL5_DBPASS_MGMT=
    - TRAVIS_PGSQL8_DBHOST=127.0.0.1
    - TRAVIS_PGSQL8_DBPORT=5432
    - TRAVIS_PGSQL8_DBUSER=deployment
    - TRAVIS_PGSQL8_DBPASS=password1
    - TRAVIS_PGSQL8_DBNAME_MGMT=postgres
    - TRAVIS_PGSQL8_DBUSER_MGMT=postgres
    - TRAVIS_PGSQL8_DBPASS_MGMT=
# use the pear package or tbe DBSteward branch specified
    - USE_PEAR_PACKAGE=false
    - DBSTEWARD_BRANCH=master
    - DBSTEWARD_PEAR_VERSION=1.3.6

  # matrix env vars generate a new build config per set
  # we need to run the two test groups separately due to active_sql_format_autoloader
  matrix:
    - DBSTEWARD_SQLFORMAT=pgsql8
#    - DBSTEWARD_SQLFORMAT=mysql5

before_install:
  - sudo apt-get update

install:
  - sudo apt-get install php5
  - sudo apt-get install php-pear
  - sudo apt-get install php5-pgsql
  - sudo apt-get install php5-mysql
  - php --version
  - pear version
# plugin release branches install the corresponding dbsteward pear package
# dev topic / master branches check out dbsteward instead of using the pear package
  - if [[ "$USE_PEAR_PACKAGE" == "true" ]]; then sudo pear channel-discover pear.dbsteward.org ; fi
  - if [[ "$USE_PEAR_PACKAGE" == "true" ]]; then sudo pear install "dbsteward/DBSteward-$DBSTEWARD_PEAR_VERSION" ; fi
  - if [[ "$USE_PEAR_PACKAGE" == "true" ]]; then which dbsteward ; fi
  - if [[ "$USE_PEAR_PACKAGE" == "true" ]]; then dbsteward ; fi
  - if [[ "$USE_PEAR_PACKAGE" == "false" ]]; then sudo git clone --depth=50 --branch=$DBSTEWARD_BRANCH git://github.com/nkiraly/DBSteward.git /home/travis/build/nkiraly/DBSteward ; fi
  - if [[ "$USE_PEAR_PACKAGE" == "false" ]]; then export DBSTEWARD_BINARY_LOCATION=/home/travis/build/nkiraly/DBSteward/bin/dbsteward ; fi
  - if [[ "$USE_PEAR_PACKAGE" == "false" ]]; then find /home/travis/build/nkiraly/* ; fi
  - if [[ "$USE_PEAR_PACKAGE" == "false" ]]; then /home/travis/build/nkiraly/DBSteward/bin/dbsteward ; fi


before_script:
  - mvn clean
  - mvn install
  - if [[ "$DBSTEWARD_SQLFORMAT" == "pgsql8" ]]; then psql -U postgres -d postgres -c "CREATE USER dbsteward_ci WITH SUPERUSER CREATEDB CREATEROLE PASSWORD 'password1';" ; fi
  - if [[ "$DBSTEWARD_SQLFORMAT" == "pgsql8" ]]; then PGPASSWORD=password1 psql -U dbsteward_ci -d postgres -c "CREATE DATABASE someapp TEMPLATE template0 ENCODING 'UTF8';" ; fi
  #- if [[ "$DBSTEWARD_SQLFORMAT" == "pgsql8" ]]; then PGPASSWORD=password1 psql -U dbsteward_ci -d postgres -l ; fi
  #- if [[ "$DBSTEWARD_SQLFORMAT" == "pgsql8" ]]; then PGPASSWORD=password1 psql -U dbsteward_ci -d someapp -c "SELECT * FROM pg_language;" ; fi
  - if [[ "$DBSTEWARD_SQLFORMAT" == "pgsql8" ]]; then PGPASSWORD=password1 psql -U dbsteward_ci -d someapp -c "CREATE ROLE someapp;" ; fi
  - if [[ "$DBSTEWARD_SQLFORMAT" == "pgsql8" ]]; then PGPASSWORD=password1 psql -U dbsteward_ci -d someapp -c "CREATE ROLE someapp_readonly;" ; fi
  - if [[ "$DBSTEWARD_SQLFORMAT" == "pgsql8" ]]; then PGPASSWORD=password1 psql -U dbsteward_ci -d postgres -c "DROP DATABASE someapp;" ; fi


# by default, travis runs "mvn test", but we want to make sure that after installing the plugin, the examples work
script: ./script/ci/run_examples.sh
